create PROCEDURE GET_ACTIVATION_KEY_FOR_USER(
    id_in IN USERS.ID%TYPE,
    response OUT CODES.ACTIVATION_CODE%TYPE)
IS
BEGIN
    SELECT ACTIVATION_CODE INTO response FROM CODES
    INNER JOIN USER_CODES ON CODES.ID = USER_CODES.CODE_ID
    INNER JOIN USERS ON USER_CODES.USER_ID = USERS.ID
    WHERE USERS.ID = id_in;
END;
/

