create PROCEDURE GET_ALL_SENDERS_V2(
    id_in IN USERS.ID%TYPE,
    response OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN response FOR
        SELECT min(ID), FIRST_NAME FROM USERS
            INNER JOIN USER_MESSAGES ON USERS.ID = USER_MESSAGES.SENDER_ID
            WHERE USER_MESSAGES.RECEIVER_ID = id_in
            GROUP BY ID, FIRST_NAME;
    COMMIT;
END;
/

