create PROCEDURE GET_ALL_IMPRESSIONS_FOR_USER(
    id_in IN USERS.ID%TYPE,
    response OUT SYS_REFCURSOR)
    IS
BEGIN
    OPEN response FOR
        SELECT * FROM IMPRESSIONS
        INNER JOIN USER_IMPRESSIONS UI on IMPRESSIONS.ID = UI.IMPRESSION_ID
        INNER JOIN USERS U on UI.RECEIVER_ID = U.ID
        WHERE U.ID = id_in;
END;
/

