create PROCEDURE GET_ALL_IMPRESSIONS_FOR_USER_V2(
    id_in IN USERS.ID%TYPE,
    response OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN response FOR
    SELECT IMPRESSION AS "impression",
           SENDER_ID AS "senderId"
    FROM IMPRESSIONS
    INNER JOIN USER_IMPRESSIONS ON IMPRESSIONS.ID = USER_IMPRESSIONS.IMPRESSION_ID
    INNER JOIN USERS ON USER_IMPRESSIONS.RECEIVER_ID = USERS.ID
    WHERE USERS.ID = id_in;

END;
/

