create PROCEDURE GET_USER_DETAILS_BY_ID(
    id_in IN USERS.ID%TYPE,
    response OUT SYS_REFCURSOR)
    IS
BEGIN
    OPEN response FOR
        SELECT *
        FROM DETAILS
        INNER JOIN USER_DETAILS ON DETAILS.ID = USER_DETAILS.DETAIL_ID
        INNER JOIN USERS ON USER_DETAILS.USER_ID = USERS.ID
        WHERE USER_ID = id_in;
END;
/

