create PROCEDURE UPLOAD_AVATAR(
    id_in IN USERS.ID%TYPE,
    image_in IN DETAILS.AVATAR%TYPE)
IS
BEGIN
    UPDATE DETAILS SET AVATAR = image_in WHERE
    ID = (SELECT DETAIL_ID FROM USER_DETAILS WHERE USER_DETAILS.USER_ID = id_in);
END;
/

